import type { CalcContent, Lang } from './types';

export const UI: Record<Lang, Record<string, string>> = {
  en: {
    appName:'Paisa Saathi', tagline:'Your family money helper',
    heroP:'Simple money calculators for Indian families. We explain first, then calculate — in plain language.',
    secLoans:'Loans', secLoansSub:'Borrow smart. Pay less interest.',
    secInvest:'Investments', secInvestSub:'Grow your savings steadily.',
    secRetire:'Retirement', secRetireSub:'Plan for a worry-free later life.',
    whatIs:'What is this?', whyMatter:'Why it matters', exampleH:'A simple example',
    yourInputs:'Your numbers', results:'Your result', whatThisMeans:'What this means for you',
    nextStep:'Suggested next step', learn30:'Learn in 30 seconds', back:'All calculators',
    addLoan:'+ Add another loan', remove:'Remove', loanName:'Loan name',
    footerNote:'Educational estimates only — not financial advice.', footerHome:'Back to home',
    openCalc:'Open', goTo:'Go to', resetEg:'Reset to example', builtBy:'Built by',
    yrsShort:'yrs'
  },
  hi: {
    appName:'पैसा साथी', tagline:'आपके परिवार का पैसा साथी',
    heroP:'भारतीय परिवारों के लिए आसान पैसे के कैलकुलेटर। पहले समझाते हैं, फिर हिसाब करते हैं — बिल्कुल सरल भाषा में।',
    secLoans:'लोन', secLoansSub:'समझदारी से उधार लें। कम ब्याज दें।',
    secInvest:'निवेश (Investment)', secInvestSub:'अपनी बचत को धीरे-धीरे बढ़ाएँ।',
    secRetire:'रिटायरमेंट', secRetireSub:'बुढ़ापे की चिंता-मुक्त तैयारी करें।',
    whatIs:'यह क्या है?', whyMatter:'यह क्यों ज़रूरी है', exampleH:'एक आसान उदाहरण',
    yourInputs:'आपके आँकड़े', results:'आपका नतीजा', whatThisMeans:'इसका आपके लिए मतलब',
    nextStep:'आगे क्या करें', learn30:'30 सेकंड में समझें', back:'सभी कैलकुलेटर',
    addLoan:'+ एक और लोन जोड़ें', remove:'हटाएँ', loanName:'लोन का नाम',
    footerNote:'सिर्फ़ जानकारी के लिए अनुमान — यह वित्तीय सलाह नहीं है।', footerHome:'होम पर वापस',
    openCalc:'खोलें', goTo:'जाएँ', resetEg:'उदाहरण पर रीसेट करें', builtBy:'बनाया',
    yrsShort:'साल'
  }
};

export const C: Record<string, Record<Lang, CalcContent>> = {
  emi: {
    en:{ t:'EMI Calculator', s:'Find your monthly loan payment',
      what:'EMI means "Equated Monthly Instalment" — the fixed amount you pay the bank every month until the loan is over.',
      why:'Before taking any loan, you should know the EMI so you can be sure it fits comfortably in your monthly budget.',
      eg:'You take a ₹30 lakh home loan at 8.5% for 20 years. Your EMI is about ₹26,000 every month for 240 months.',
      in:{ amount:{l:'Loan amount', h:'How much you want to borrow'}, rate:{l:'Interest rate', h:'Yearly rate the bank charges'}, years:{l:'Tenure (years)', h:'How long to repay'} },
      res:{ emi:'Monthly EMI', interest:'Total interest you pay', total:'Total amount repaid' },
      learn:[{q:'Why is total repayment more than the loan?', a:'Because you also pay interest every month. The longer the tenure, the more total interest you pay.'}] },
    hi:{ t:'EMI कैलकुलेटर', s:'अपनी महीने की किस्त जानें',
      what:'EMI यानी हर महीने की तय किस्त — वह रकम जो आप लोन ख़त्म होने तक हर महीने बैंक को देते हैं।',
      why:'कोई भी लोन लेने से पहले EMI पता होनी चाहिए, ताकि आप देख सकें कि यह आपके महीने के बजट में आराम से बैठती है या नहीं।',
      eg:'आप 8.5% पर 20 साल के लिए ₹30 लाख का होम लोन लेते हैं। आपकी EMI लगभग ₹26,000 हर महीने, 240 महीनों तक होगी।',
      in:{ amount:{l:'लोन राशि', h:'आप कितना उधार लेना चाहते हैं'}, rate:{l:'ब्याज दर (Interest)', h:'बैंक की सालाना दर'}, years:{l:'अवधि (साल)', h:'कितने साल में चुकाना है'} },
      res:{ emi:'महीने की EMI', interest:'कुल ब्याज जो आप देंगे', total:'कुल चुकाई गई राशि' },
      learn:[{q:'कुल चुकाई राशि लोन से ज़्यादा क्यों है?', a:'क्योंकि आप हर महीने ब्याज भी देते हैं। अवधि जितनी लंबी, कुल ब्याज उतना ज़्यादा।'}] }
  },
  prepay: {
    en:{ t:'Loan Prepayment Calculator', s:'See how much paying extra saves you',
      what:'Prepayment means paying a little extra towards your loan each month, on top of your EMI.',
      why:'Even a small extra amount goes straight to reducing your loan, so you finish years earlier and save a lot of interest.',
      eg:'On a ₹25 lakh loan at 9%, paying just ₹5,000 extra each month can finish the loan ~5 years sooner and save lakhs in interest.',
      in:{ outstanding:{l:'Remaining loan amount', h:'What you still owe today'}, rate:{l:'Interest rate', h:'Yearly rate'}, years:{l:'Remaining tenure (years)', h:'Years left as per schedule'}, extra:{l:'Extra payment each month', h:'On top of your normal EMI'} },
      res:{ saved:'Interest you save', yrsSaved:'Time you save', newterm:'New payoff time' },
      learn:[{q:'Is prepayment always good?', a:'Usually yes for high-interest loans. But keep an emergency fund first, and check your bank does not charge a prepayment penalty.'}] },
    hi:{ t:'लोन Prepayment कैलकुलेटर', s:'थोड़ा ज़्यादा देने से कितनी बचत होगी',
      what:'Prepayment यानी अपनी EMI के अलावा हर महीने लोन में थोड़ा अतिरिक्त पैसा डालना।',
      why:'छोटी सी अतिरिक्त रकम भी सीधे लोन घटाती है, इसलिए आप कई साल पहले फ़्री हो जाते हैं और बहुत सारा ब्याज बचा लेते हैं।',
      eg:'₹25 लाख के लोन पर 9% पर, हर महीने सिर्फ़ ₹5,000 अतिरिक्त देने से लोन ~5 साल जल्दी ख़त्म और लाखों का ब्याज बचत।',
      in:{ outstanding:{l:'बाकी लोन राशि', h:'आज आप पर कितना बकाया है'}, rate:{l:'ब्याज दर', h:'सालाना दर'}, years:{l:'बची हुई अवधि (साल)', h:'शेड्यूल के अनुसार बचे साल'}, extra:{l:'हर महीने अतिरिक्त भुगतान', h:'आपकी सामान्य EMI के ऊपर'} },
      res:{ saved:'बचाया गया ब्याज', yrsSaved:'बचाया गया समय', newterm:'अब कितने साल में पूरा' },
      learn:[{q:'क्या Prepayment हमेशा अच्छा है?', a:'ऊँचे ब्याज वाले लोन के लिए आमतौर पर हाँ। पर पहले आपातकालीन फंड रखें, और देख लें कि बैंक prepayment पर शुल्क तो नहीं लेता।'}] }
  },
  whichfirst: {
    en:{ t:'Which Loan Should I Repay First?', s:'Order your loans the smart way',
      what:'When you have many loans, this tells you which one to clear first to save the most money.',
      why:'Clearing your highest-interest loan first saves the most interest. This is the simple, proven method.',
      eg:'A 14% personal loan costs you far more than an 8.5% home loan. Pay extra on the 14% one first.',
      in:{}, res:{}, learn:[{q:'What if a small loan is at low interest?', a:'Closing a tiny loan can feel good and free up an EMI. But mathematically, the highest interest rate should usually go first.'}] },
    hi:{ t:'कौन सा लोन पहले चुकाऊँ?', s:'अपने लोन समझदारी से क्रम में लगाएँ',
      what:'जब आपके कई लोन हों, यह बताता है कि सबसे ज़्यादा पैसा बचाने के लिए पहले कौन सा ख़त्म करें।',
      why:'सबसे ऊँचे ब्याज वाला लोन पहले ख़त्म करने से सबसे ज़्यादा ब्याज बचता है। यह आसान और आज़माया हुआ तरीका है।',
      eg:'14% का personal loan, 8.5% के home loan से कहीं ज़्यादा महँगा पड़ता है। पहले 14% वाले पर अतिरिक्त भुगतान करें।',
      in:{}, res:{}, learn:[{q:'अगर छोटा लोन कम ब्याज पर हो तो?', a:'छोटा लोन बंद करना अच्छा लगता है और एक EMI मुक्त हो जाती है। पर गणित कहता है — सबसे ऊँचा ब्याज पहले।'}] }
  },
  fdvsloan: {
    en:{ t:'FD vs Loan Repayment', s:'Keep the FD, or clear the loan?',
      what:'You have some spare money. Should you put it in a Fixed Deposit, or use it to repay your loan?',
      why:'An FD earns you interest (and you pay tax on it). A loan charges you interest. Comparing the two — after tax — tells you the better choice.',
      eg:'If your loan costs 9% but your FD earns only 5.6% after tax, repaying the loan clearly saves more.',
      in:{ amount:{l:'Spare amount', h:'Money you can use'}, fd:{l:'FD interest rate', h:'What the FD pays per year'}, loan:{l:'Loan interest rate', h:'What your loan charges'}, tax:{l:'Your tax bracket', h:'0, 5, 10, 20 or 30'} },
      res:{ efffd:'FD return after tax', effloan:'Your loan cost', diff:'Yearly benefit of the better choice' },
      learn:[{q:'Why subtract tax from FD?', a:'FD interest is added to your income and taxed. So a 7% FD in the 30% bracket really gives you about 4.9%.'}] },
    hi:{ t:'FD बनाम लोन चुकाना', s:'FD रखें, या लोन ख़त्म करें?',
      what:'आपके पास कुछ अतिरिक्त पैसा है। उसे Fixed Deposit (FD) में रखें, या लोन चुकाने में लगाएँ?',
      why:'FD आपको ब्याज देती है (जिस पर टैक्स लगता है)। लोन आपसे ब्याज लेता है। टैक्स के बाद दोनों की तुलना सही रास्ता दिखाती है।',
      eg:'अगर लोन 9% का है पर FD टैक्स के बाद सिर्फ़ 5.6% देती है, तो लोन चुकाना साफ़ तौर पर ज़्यादा बचत है।',
      in:{ amount:{l:'अतिरिक्त राशि', h:'जो पैसा आप लगा सकते हैं'}, fd:{l:'FD ब्याज दर', h:'FD सालाना कितना देती है'}, loan:{l:'लोन ब्याज दर', h:'लोन कितना ब्याज लेता है'}, tax:{l:'आपका टैक्स ब्रैकेट', h:'0, 5, 10, 20 या 30'} },
      res:{ efffd:'टैक्स के बाद FD रिटर्न', effloan:'आपके लोन की लागत', diff:'बेहतर विकल्प से सालाना फ़ायदा' },
      learn:[{q:'FD से टैक्स क्यों घटाएँ?', a:'FD का ब्याज आपकी आय में जुड़कर टैक्स लगता है। तो 30% ब्रैकेट में 7% की FD असल में करीब 4.9% ही देती है।'}] }
  },
  investvsrepay: {
    en:{ t:'Invest vs Repay Loan', s:'Grow money, or become debt-free?',
      what:'You have spare money every month. Should you invest it for growth, or use it to repay your loan faster?',
      why:'Repaying a loan gives a guaranteed saving equal to the loan rate. Investing may earn more — but is not guaranteed. Your risk comfort and time decide.',
      eg:'Loan at 9% vs an equity fund that may give ~12% over 10+ years: a balanced person might invest, a cautious one might repay.',
      in:{ loan:{l:'Loan interest rate', h:'What your loan charges'}, ret:{l:'Expected investment return', h:'Realistic long-term return'}, horizon:{l:'How many years you can stay invested', h:'Longer is safer for equity'} },
      res:{ conservative:'If you are cautious', balanced:'If you are balanced', aggressive:'If you are comfortable with risk' },
      learn:[{q:'Why does time horizon matter?', a:'Over short periods markets can fall. Over 7–10+ years, equity has historically smoothed out and often beaten loan rates.'}] },
    hi:{ t:'निवेश करें या लोन चुकाएँ', s:'पैसा बढ़ाएँ, या कर्ज़-मुक्त बनें?',
      what:'हर महीने आपके पास कुछ अतिरिक्त पैसा है। उसे बढ़ने के लिए निवेश करें, या लोन जल्दी चुकाने में लगाएँ?',
      why:'लोन चुकाना लोन की दर के बराबर पक्की बचत देता है। निवेश शायद ज़्यादा कमाए — पर पक्का नहीं। आपका जोखिम-आराम और समय तय करते हैं।',
      eg:'9% का लोन बनाम equity fund जो 10+ साल में ~12% दे सकता है: संतुलित व्यक्ति निवेश कर सकता है, सतर्क व्यक्ति लोन चुका सकता है।',
      in:{ loan:{l:'लोन ब्याज दर', h:'लोन कितना ब्याज लेता है'}, ret:{l:'अपेक्षित निवेश रिटर्न', h:'व्यावहारिक लंबे समय का रिटर्न'}, horizon:{l:'कितने साल निवेशित रह सकते हैं', h:'equity के लिए ज़्यादा समय सुरक्षित'} },
      res:{ conservative:'अगर आप सतर्क हैं', balanced:'अगर आप संतुलित हैं', aggressive:'अगर आप जोखिम में सहज हैं' },
      learn:[{q:'समय-अवधि क्यों मायने रखती है?', a:'कम समय में बाज़ार गिर सकता है। 7–10+ साल में equity ने अक्सर उतार-चढ़ाव संभाला है और लोन दर से बेहतर दिया है।'}] }
  },
  sip: {
    en:{ t:'SIP Calculator', s:'See your monthly investing grow',
      what:'SIP means investing a fixed amount in a mutual fund every month, automatically.',
      why:'Small monthly amounts, invested patiently, grow into a large sum because your returns also start earning returns — this is compounding.',
      eg:'₹10,000 a month for 15 years at 12% can grow to about ₹50 lakh, even though you invested only ₹18 lakh.',
      in:{ monthly:{l:'Monthly investment', h:'Amount you invest each month'}, ret:{l:'Expected return', h:'Realistic yearly return'}, years:{l:'Number of years', h:'How long you keep investing'} },
      res:{ invested:'Total you invest', fv:'Final value', gain:'Wealth gained' },
      learn:[{q:'What return should I expect?', a:'Equity mutual funds have historically given ~11–13% over long periods, but it is not guaranteed and varies year to year.'}] },
    hi:{ t:'SIP कैलकुलेटर', s:'अपने महीने के निवेश को बढ़ता देखें',
      what:'SIP यानी हर महीने अपने-आप एक तय रकम mutual fund में निवेश करना।',
      why:'छोटी मासिक रकमें, धैर्य से निवेश करने पर, बड़ी रकम बन जाती हैं क्योंकि आपका रिटर्न भी रिटर्न कमाने लगता है — इसे compounding कहते हैं।',
      eg:'12% पर 15 साल तक ₹10,000 महीना करीब ₹50 लाख बन सकता है, जबकि आपने सिर्फ़ ₹18 लाख लगाए।',
      in:{ monthly:{l:'मासिक निवेश', h:'हर महीने कितना निवेश'}, ret:{l:'अपेक्षित रिटर्न', h:'व्यावहारिक सालाना रिटर्न'}, years:{l:'कितने साल', h:'कितने समय तक निवेश करेंगे'} },
      res:{ invested:'कुल निवेश', fv:'अंतिम मूल्य', gain:'बनी हुई संपत्ति' },
      learn:[{q:'कितने रिटर्न की उम्मीद रखूँ?', a:'Equity mutual funds ने लंबे समय में करीब 11–13% दिया है, पर यह पक्का नहीं और हर साल बदलता है।'}] }
  },
  lumpsum: {
    en:{ t:'Lumpsum Calculator', s:'Grow a one-time investment',
      what:'A lumpsum is a single one-time investment, instead of investing every month.',
      why:'If you receive a bonus, maturity amount or sale proceeds, this shows how much it can become if invested and left to grow.',
      eg:'₹5 lakh invested once at 12% becomes about ₹15.5 lakh in 10 years.',
      in:{ amount:{l:'Investment amount', h:'One-time amount you invest'}, ret:{l:'Expected return', h:'Realistic yearly return'}, years:{l:'Number of years', h:'How long you stay invested'} },
      res:{ fv:'Future value', gain:'Total gain' },
      learn:[{q:'Lumpsum or SIP?', a:'SIP suits regular salary saving and reduces timing risk. Lumpsum suits money you already have and can leave invested long term.'}] },
    hi:{ t:'Lumpsum कैलकुलेटर', s:'एकमुश्त निवेश को बढ़ाएँ',
      what:'Lumpsum यानी हर महीने के बजाय एक बार में किया गया एकमुश्त निवेश।',
      why:'अगर आपको बोनस, मैच्योरिटी या बिक्री से पैसा मिले, यह दिखाता है कि निवेश करके छोड़ देने पर वह कितना बन सकता है।',
      eg:'12% पर एक बार लगाए ₹5 लाख, 10 साल में करीब ₹15.5 लाख बन जाते हैं।',
      in:{ amount:{l:'निवेश राशि', h:'एक बार में कितना निवेश'}, ret:{l:'अपेक्षित रिटर्न', h:'व्यावहारिक सालाना रिटर्न'}, years:{l:'कितने साल', h:'कितने समय निवेशित रहेंगे'} },
      res:{ fv:'भविष्य का मूल्य', gain:'कुल फ़ायदा' },
      learn:[{q:'Lumpsum या SIP?', a:'SIP नियमित वेतन-बचत के लिए ठीक है और समय का जोखिम घटाती है। Lumpsum उस पैसे के लिए जो पहले से है और लंबे समय छोड़ सकते हैं।'}] }
  },
  goal: {
    en:{ t:'Goal Planner', s:'How much to invest for a dream',
      what:'A goal is a future need — your child’s education, a wedding, a house, or retirement. This finds the monthly SIP to reach it.',
      why:'Knowing the exact monthly amount turns a big scary goal into a simple, doable habit.',
      eg:'To build ₹50 lakh for your child’s education in 15 years at 12%, you need to invest about ₹10,000 a month.',
      in:{ target:{l:'Goal amount needed', h:'How much you will need'}, years:{l:'Years left for the goal', h:'Time until you need the money'}, ret:{l:'Expected return', h:'Realistic yearly return'} },
      res:{ sip:'Monthly SIP needed', invested:'Total you will invest', gain:'Growth on top' },
      learn:[{q:'What if I cannot afford the full SIP?', a:'Start with what you can and increase it every year as your income grows. Even a smaller start beats not starting.'}] },
    hi:{ t:'Goal प्लानर', s:'किसी सपने के लिए कितना निवेश करें',
      what:'Goal यानी भविष्य की ज़रूरत — बच्चे की पढ़ाई, शादी, घर, या रिटायरमेंट। यह उस तक पहुँचने की मासिक SIP बताता है।',
      why:'सही मासिक रकम पता चलने से बड़ा डरावना लक्ष्य एक आसान, करने लायक आदत बन जाता है।',
      eg:'बच्चे की पढ़ाई के लिए 15 साल में ₹50 लाख बनाने हेतु 12% पर करीब ₹10,000 महीना निवेश चाहिए।',
      in:{ target:{l:'ज़रूरी लक्ष्य राशि', h:'आपको कितना चाहिए होगा'}, years:{l:'लक्ष्य के लिए बचे साल', h:'पैसे की ज़रूरत में कितना समय'}, ret:{l:'अपेक्षित रिटर्न', h:'व्यावहारिक सालाना रिटर्न'} },
      res:{ sip:'ज़रूरी मासिक SIP', invested:'कुल निवेश', gain:'ऊपर से बढ़ोतरी' },
      learn:[{q:'अगर पूरी SIP न दे पाऊँ?', a:'जितना कर सकें उतने से शुरू करें और हर साल आय बढ़ने पर बढ़ाएँ। छोटी शुरुआत भी न शुरू करने से बेहतर है।'}] }
  },
  retirecorpus: {
    en:{ t:'Retirement Corpus Calculator', s:'How big a nest egg you need',
      what:'Corpus means the total savings you should have on the day you retire, to live without a salary.',
      why:'Prices keep rising (inflation), so the expenses you have today will cost much more by the time you retire. You must plan for that bigger number.',
      eg:'₹40,000 monthly expense today, with 6% inflation over 20 years, becomes about ₹1.28 lakh a month — needing a corpus of roughly ₹3.8 crore.',
      in:{ age:{l:'Your current age', h:'How old you are now'}, retage:{l:'Retirement age', h:'When you plan to stop working'}, expense:{l:'Monthly expenses today', h:'What you spend per month now'}, infl:{l:'Inflation rate', h:'Yearly price rise, usually 5–7%'} },
      res:{ futexp:'Your monthly expense at retirement', corpus:'Corpus you should aim for' },
      learn:[{q:'What is inflation, simply?', a:'It is how prices slowly rise over time. ₹100 today buys less after 10 years. That is why future expenses look so much bigger.'}] },
    hi:{ t:'Retirement Corpus कैलकुलेटर', s:'रिटायरमेंट के लिए कितनी जमा-पूँजी चाहिए',
      what:'Corpus यानी रिटायरमेंट के दिन आपके पास जो कुल जमा राशि होनी चाहिए, ताकि बिना वेतन के जीवन चले।',
      why:'दाम बढ़ते रहते हैं (inflation/महँगाई), इसलिए आज के खर्च रिटायरमेंट तक बहुत ज़्यादा हो जाएँगे। उस बड़ी रकम की तैयारी ज़रूरी है।',
      eg:'आज ₹40,000 मासिक खर्च, 6% महँगाई पर 20 साल बाद करीब ₹1.28 लाख महीना बन जाता है — जिसके लिए करीब ₹3.8 करोड़ का corpus चाहिए।',
      in:{ age:{l:'आपकी अभी की उम्र', h:'अभी आप कितने साल के हैं'}, retage:{l:'रिटायरमेंट की उम्र', h:'कब काम बंद करना है'}, expense:{l:'आज का मासिक खर्च', h:'अभी आप महीने में कितना खर्च करते हैं'}, infl:{l:'महँगाई दर (Inflation)', h:'सालाना दाम बढ़ोतरी, आमतौर पर 5–7%'} },
      res:{ futexp:'रिटायरमेंट के समय मासिक खर्च', corpus:'जितना corpus लक्ष्य रखें' },
      learn:[{q:'महँगाई आसान शब्दों में क्या है?', a:'समय के साथ दाम धीरे-धीरे बढ़ना। आज का ₹100, 10 साल बाद कम चीज़ें ख़रीदता है। इसलिए भविष्य के खर्च इतने बड़े दिखते हैं।'}] }
  },
  swp: {
    en:{ t:'SWP Calculator', s:'Steady monthly income from savings',
      what:'SWP (Systematic Withdrawal Plan) means taking a fixed amount out of your investment every month, like a self-made pension.',
      why:'After retirement, your corpus keeps earning returns while you withdraw. This shows how long the money can last.',
      eg:'A ₹1 crore corpus earning 8%, withdrawing ₹75,000 a month, lasts about 28 years.',
      in:{ corpus:{l:'Your total corpus', h:'Money you start with'}, withdraw:{l:'Monthly withdrawal', h:'Amount you take out each month'}, ret:{l:'Expected return', h:'What the corpus earns per year'} },
      res:{ years:'How long the money lasts' },
      learn:[{q:'Can the money last forever?', a:'If your withdrawals are smaller than what the corpus earns, the balance can keep growing and last indefinitely.'}] },
    hi:{ t:'SWP कैलकुलेटर', s:'बचत से हर महीने नियमित आमदनी',
      what:'SWP यानी अपने निवेश से हर महीने एक तय रकम निकालना — जैसे खुद की बनाई पेंशन।',
      why:'रिटायरमेंट के बाद आपका corpus रिटर्न कमाता रहता है और आप निकासी करते हैं। यह दिखाता है पैसा कितने समय चलेगा।',
      eg:'₹1 करोड़ का corpus 8% कमाते हुए, ₹75,000 महीना निकालने पर करीब 28 साल चलता है।',
      in:{ corpus:{l:'आपका कुल corpus', h:'जितने पैसे से शुरुआत'}, withdraw:{l:'मासिक निकासी', h:'हर महीने कितना निकालेंगे'}, ret:{l:'अपेक्षित रिटर्न', h:'corpus सालाना कितना कमाता है'} },
      res:{ years:'पैसा कितने समय चलेगा' },
      learn:[{q:'क्या पैसा हमेशा चल सकता है?', a:'अगर आपकी निकासी, corpus की कमाई से कम है, तो बैलेंस बढ़ता रह सकता है और अनिश्चित काल तक चल सकता है।'}] }
  },
  canretire: {
    en:{ t:'Can I Retire?', s:'Check your retirement readiness',
      what:'This gives you a simple readiness score, the gap (if any) in your savings, and what to invest monthly to close it.',
      why:'It turns a vague worry — "am I saving enough?" — into a clear number you can act on today.',
      eg:'If you need ₹4 crore but are on track for ₹2.5 crore, you have a gap — and we show the monthly SIP to fix it.',
      in:{ age:{l:'Your current age', h:'How old you are now'}, retage:{l:'Retirement age', h:'When you plan to retire'}, savings:{l:'Investments you have today', h:'Current total savings/investments'}, expense:{l:'Monthly expenses today', h:'What you spend now'} },
      res:{ score:'Readiness score', gap:'Corpus gap', sip:'Suggested monthly investment' },
      learn:[{q:'What does the score mean?', a:'100 means you are fully on track. Below 100 means you have a gap — the suggested SIP shows how to reach 100.'}] },
    hi:{ t:'क्या मैं रिटायर हो सकता हूँ?', s:'अपनी रिटायरमेंट तैयारी जाँचें',
      what:'यह एक आसान readiness स्कोर, बचत में कमी (अगर है), और उसे पूरा करने हेतु मासिक निवेश बताता है।',
      why:'यह "क्या मैं काफ़ी बचा रहा हूँ?" की धुंधली चिंता को एक साफ़ नंबर में बदल देता है जिस पर आज कार्रवाई हो सके।',
      eg:'अगर आपको ₹4 करोड़ चाहिए पर ट्रैक ₹2.5 करोड़ का है, तो कमी है — और हम उसे पूरा करने की मासिक SIP बताते हैं।',
      in:{ age:{l:'आपकी अभी की उम्र', h:'अभी आप कितने साल के हैं'}, retage:{l:'रिटायरमेंट उम्र', h:'कब रिटायर होना है'}, savings:{l:'आज के निवेश', h:'मौजूदा कुल बचत/निवेश'}, expense:{l:'आज का मासिक खर्च', h:'अभी कितना खर्च करते हैं'} },
      res:{ score:'Readiness स्कोर', gap:'Corpus में कमी', sip:'सुझाई गई मासिक निवेश' },
      learn:[{q:'स्कोर का मतलब क्या है?', a:'100 यानी आप पूरी तरह ट्रैक पर हैं। 100 से कम यानी कमी है — सुझाई गई SIP बताती है 100 तक कैसे पहुँचें।'}] }
  },
  willlast: {
    en:{ t:'Will My Money Last?', s:'Find the age your corpus may run out',
      what:'This shows up to what age your retirement savings are likely to support you, considering rising prices.',
      why:'The biggest retirement fear is outliving your money. This gives you a clear age to plan around.',
      eg:'A ₹3 crore corpus, ₹80,000 monthly expense, 6% inflation and 8% return may last to about age 88.',
      in:{ age:{l:'Your age at retirement', h:'Age when withdrawals begin'}, corpus:{l:'Retirement corpus', h:'Total savings at retirement'}, expense:{l:'Monthly expenses', h:'Monthly spending at retirement'}, infl:{l:'Inflation rate', h:'Yearly price rise'}, ret:{l:'Expected return', h:'What the corpus earns'} },
      res:{ lastage:'Your money may last until age' },
      learn:[{q:'Why does inflation shorten it?', a:'Your expenses rise every year, so you withdraw more over time. That drains the corpus faster than a fixed amount would.'}] },
    hi:{ t:'क्या मेरा पैसा चलेगा?', s:'जानें किस उम्र तक corpus चलेगा',
      what:'यह दिखाता है कि बढ़ते दामों को देखते हुए आपकी रिटायरमेंट बचत किस उम्र तक साथ देगी।',
      why:'रिटायरमेंट का सबसे बड़ा डर है — पैसा पहले ख़त्म हो जाना। यह योजना बनाने के लिए एक साफ़ उम्र देता है।',
      eg:'₹3 करोड़ corpus, ₹80,000 मासिक खर्च, 6% महँगाई और 8% रिटर्न पर करीब 88 साल की उम्र तक चल सकता है।',
      in:{ age:{l:'रिटायरमेंट पर आपकी उम्र', h:'जिस उम्र में निकासी शुरू'}, corpus:{l:'रिटायरमेंट corpus', h:'रिटायरमेंट पर कुल बचत'}, expense:{l:'मासिक खर्च', h:'रिटायरमेंट पर मासिक खर्च'}, infl:{l:'महँगाई दर', h:'सालाना दाम बढ़ोतरी'}, ret:{l:'अपेक्षित रिटर्न', h:'corpus कितना कमाता है'} },
      res:{ lastage:'इस उम्र तक पैसा चल सकता है' },
      learn:[{q:'महँगाई इसे क्यों घटाती है?', a:'हर साल खर्च बढ़ता है, तो समय के साथ आप ज़्यादा निकालते हैं। इससे corpus तय रकम की तुलना में जल्दी ख़त्म होता है।'}] }
  }
};

export const GOAL_PRESETS: { en: string; hi: string; target: number; years: number }[] = [
  { en:'Child Education', hi:'बच्चे की पढ़ाई', target:5000000, years:15 },
  { en:'Child Marriage', hi:'बच्चे की शादी', target:3000000, years:18 },
  { en:'House Purchase', hi:'घर ख़रीदना', target:8000000, years:10 },
  { en:'Retirement', hi:'रिटायरमेंट', target:30000000, years:20 },
  { en:'Custom Goal', hi:'अपना लक्ष्य', target:5000000, years:15 }
];
